name: Python CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install flit
        run: |
          python -m pip install --upgrade pip
          pip install flit

      - name: Build and publish to PyPI
        run: |
          flit build
          flit publish --username __token__ --password "${{ secrets.PYPI_PASSWORD }}"
